### ISSUE TITLE
Thuộc tính

### ISSUE THREAD

**Issue by lvman** [lvman/contactsapp#2]

**Comment by lvman** [comment]
Dùng thuộc tính thay cho các hàm get, set
Kiểm tra độ dài của ký tự khi nhập vào:
- Họ, tên thì không quá 10 ký tự
- Địa chỉ không quá 50 ký tự
- Số điện thoại không quá 12 ký tự

**Comment by lvman** [comment]
Dùng thuộc tính thay cho các hàm get, set.
Kiểm tra độ dài của ký tự khi được gán vào:
- Họ, tên thì không dài quá 10 ký tự
- Địa chỉ thì không quá 50 ký tự
- Số điện thoại thì không quá 12 ký tự

**Comment by manleviet** [comment]
Ok sẽ làm
